apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq
  labels:
    component: rabbitmq
    project: roboshop
    tier: database
type: Opaque
data:
  RABBITMQ_DEFAULT_USER: roboshop
  RABBITMQ_DEFAULT_PASS: roboshop123
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  Namespace: roboshop
  #replica set labels
  labels:
    component: rabbitmq
    project: roboshop
    tier: database
spec:
  replicas: 1
  # these are the labels replica set use to create pod replicas,this should match pod lables
  selector:
    matchLabels:
      component: rabbitmq
      project: roboshop
      tier: database
  # this is pod definition
  template:
    metadata:
      labels:
        component: rabbitmq
        project: roboshop
        tier: database
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  Namespace: roboshop
  labels:
    component: rabbitmq
    project: roboshop
    tier: database
spec: 
  selector: 
    component: rabbitmq
    project: roboshop
    tier: database
  ports:
    - protocol: TCP
      port: 5672 #service port
      targetPort: 5672 #container port